### ISSUE TITLE
Invalide byte sequence in UTF-8

### ISSUE THREAD

**Issue by borisschapira** [nhoizey/jekyll-postfiles#1] opened 2016-08-04 10:11 UTC
Hi, I have an error even before building, just executing `jekyll doctor`.

```
Error: could not read file /Users/boris/Projects/perso/blog/jekyll-private/_posts/fr/papa/2016/2016-07-09-et-le-feu-ca-brule/1.jpg: invalid byte sequence in UTF-8
```

The same error is produced when I try to `serve` in verbose mode, I got this:

```
       ...
       EntryFilter: excluded /scripts
       EntryFilter: excluded /tasks
       EntryFilter: excluded /vendor
           Reading: _posts/en/default/2005-01-01-typo-test/2005-01-01-typo-test.md
           Reading: _posts/en/default/2014/2014-03-13-conquering-ab-testing/2014-03-13-conquering-ab-testing.md
           ... 
           ...
           Reading: _posts/fr/papa/2016/2016-07-01-esperanto/2016-07-01-esperanto.md
           Reading: _posts/fr/papa/2016/2016-07-09-et-le-feu-ca-brule/1.jpg
             Error: could not read file /Users/boris/Projects/perso/blog/jekyll-private/_posts/fr/papa/2016/2016-07-09-et-le-feu-ca-brule/1.jpg: invalid byte sequence in UTF-8
           Reading: _posts/fr/papa/2016/2016-07-09-et-le-feu-ca-brule/2016-07-09-et-le-feu-ca-brule.md
           Reading: _posts/fr/papa/2016/2016-07-10-tonton-et-tatie/2016-07-10-tonton-et-tatie.md
           ...
           ...
          Reading: _confs/sensibilisation-web.md
           Reading: _confs/web-disruption-continue.md
         Rendering: 2016/index.html
  Pre-Render Hooks: 2016/index.html
  Rendering Liquid: 2016/index.html
  Rendering Markup: 2016/index.html
  Rendering Layout: 2016/index.html
         Rendering: _posts/fr/default/2016/2016-06-15-conseils-pour-les-etudiants/2016-06-15-conseils-pour-les-etudiants.md
  Pre-Render Hooks: _posts/fr/default/2016/2016-06-15-conseils-pour-les-etudiants/2016-06-15-conseils-pour-les-etudiants.md
  Rendering Liquid: _posts/fr/default/2016/2016-06-15-conseils-pour-les-etudiants/2016-06-15-conseils-pour-les-etudiants.md
  Rendering Markup: _posts/fr/default/2016/2016-06-15-conseils-pour-les-etudiants/2016-06-15-conseils-pour-les-etudiants.md
         Requiring: kramdown
         Rendering: _posts/fr/papa/2016/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans.md
  Pre-Render Hooks: _posts/fr/papa/2016/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans.md
  Rendering Liquid: _posts/fr/papa/2016/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans.md
  Rendering Markup: _posts/fr/papa/2016/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans/2016-06-26-la-blockchain-expliquee-a-un-enfant-de-cinq-ans.md
  Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/archives-year.html
jekyll 3.2.0 | Error:  undefined method `gsub' for nil:NilClass
```

**Comment by borisschapira** [comment] 2016-08-04 10:21
I don't know why Jekyll tries to parse the images. Maybe something's missing in my conf or maybe it's because of my scoping (https://github.com/borisschapira/jekyll/blob/master/_config.yml#L13).

**Comment by nhoizey** [comment] 2016-08-04 10:21
It looks like it's the same issue as here: https://github.com/jekyll/jekyll/issues/5181#issuecomment-237314719

I don't understand, I don't have this issue on my side.

**Comment by nhoizey** [comment] 2016-08-04 10:23
I have this:

```yaml
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
```

**Comment by nhoizey** [comment] 2016-08-04 15:54
I'm still using Jekyll 3.1.6, can you try downgrading to test?

**Comment by nhoizey** [comment] 2016-08-04 16:00
There is a Zip file in this post for example:
https://nicolas-hoizey.com/2004/12/spipbackup-pour-des-sauvegardes-faciles-et-completes-de-sites-spip-ou-spip-agora.html for example

**Comment by borisschapira** [comment] 2016-08-04 16:22
Tested and reported on https://github.com/jekyll/jekyll/issues/5181#issuecomment-237314719.
What's your Ruby version ?

**Comment by nhoizey** [comment] 2016-08-04 16:30
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

**Comment by borisschapira** [comment] 2016-08-05 06:26
Same version. OS X El Capitan (I'm not uselessly curious, I'm wondering why the behaviour is different on our two computers)?

**Comment by nhoizey** [comment] 2016-08-05 06:50
That's really strange indeed, and you're not the only one with this issue…

**Comment by borisschapira** [comment] 2016-08-05 07:28
Ok so I just sent you my folder and you encounter the issue too. So in fact, you're the only one not having it 😄

**Comment by nhoizey** [comment] 2016-08-05 07:32
Trying with a fresh install on my Mac, and no issue:

```shell
$ jekyll new utf8
New jekyll site installed in /Users/nhoizey/Dropbox/Personnel/Devs/_bac_a_sable/utf8.

$ cd utf8

$ echo "gem 'jekyll-postfiles'" >> Gemfile

$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using colorator 1.1.0
Using ffi 1.9.14
Using forwardable-extended 2.6.0
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using jekyll-postfiles 2.0.0
Using minima 1.0.1
Using bundler 1.12.5
Using rb-inotify 0.9.7
Using pathutil 0.14.0
Using jekyll-sass-converter 1.4.0
Using listen 3.0.8
Using jekyll-watch 1.5.0
Using jekyll 3.2.1
Bundle complete! 3 Gemfile dependencies, 19 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ echo "gems:\n  - jekyll-postfiles" >> _config.yml

$ cp ../duty_calls.png ./_posts

$ bundle exec jekyll build
Configuration file: /Users/nhoizey/Dropbox/Personnel/Devs/_bac_a_sable/utf8/_config.yml
            Source: /Users/nhoizey/Dropbox/Personnel/Devs/_bac_a_sable/utf8
       Destination: /Users/nhoizey/Dropbox/Personnel/Devs/_bac_a_sable/utf8/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.413 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

$ ls _site/jekyll/update/2016/08/05
duty_calls.png         welcome-to-jekyll.html
```

`duty_calls.png` has been copied in `_site` without any issue…

**Comment by borisschapira** [comment] 2016-08-05 08:14
I've created a test case: [test_ut8_issue.tar.gz](https://github.com/nhoizey/jekyll-postfiles/files/403369/test_ut8_issue.tar.gz)

**Comment by borisschapira** [comment] 2016-08-05 08:15
I've created a test case: [test_ut8_issue.tar.gz](https://github.com/nhoizey/jekyll-postfiles/files/403374/test_ut8_issue.tar.gz)

**Comment by borisschapira** [comment] 2016-08-05 08:20
In my test case, I use a local installation with bundle, not using any global lib.
Have you tried?

**Comment by nhoizey** [comment] 2016-08-05 09:26
As you can see in the commands sequence, I initiated the project with my global Jekyll (3.2.1), but then used `bundle` to install and run commands.

**Comment by borisschapira** [comment] 2016-08-05 12:27
Test case updated 
[test_ut8_jekyll-postfiles.tar.gz](https://github.com/nhoizey/jekyll-postfiles/files/403727/test_ut8_jekyll-postfiles.tar.gz)

**Comment by RRMoelker** [comment] 2016-09-02 11:56
I'm having the same issue, excluding the images in the `_config` works:

```
exclude:
  - _posts/**/*.jpg
  - _posts/**/*.png
```

**Comment by borisschapira** [comment] 2016-09-04 19:21
@RRMoelker 

* Issue is solved if you are consulting the post page
* Issue is still there if you are trying to display the content of the post elsewhere, as the URL to the ressource is relative, not absolute.

![capture d ecran 2016-09-04 a 21 21 14](https://cloud.githubusercontent.com/assets/284742/18233355/857d8e2e-72e5-11e6-8e13-eda07c5576d3.png)

**Comment by RRMoelker** [comment] 2016-09-05 10:46
I was still getting the invalid byte sequence during Jekyll build. I'm using:

Ruby 2.3.0
jekyll-postfiles (2.0.0)
jekyll (3.2.0)

The problematic image was a `.png` in a sub folder `_post/<some-post>/thisOne.png`. Excluding the `.png` files worked for me. So as far I'm not experience any issues at the moment.

**Comment by nhoizey** [comment] 2016-09-05 12:38
Well, I didn't have the issue until today, with already 750 images…

One of these images, for example:
![dareboost-de-98-a-94](https://cloud.githubusercontent.com/assets/78213/18247962/049412ba-7376-11e6-94d7-789e106508ee.png)

And today, I added this image:
![2004-09-26-catching-the-sun](https://cloud.githubusercontent.com/assets/78213/18247977/1a959d68-7376-11e6-9582-fb319f34e096.jpg)

And I get this when I try to build the site:
```bash
Configuration file: _config.yml
Configuration file: _config_credentials.yml
            Source: /Users/nhoizey/Dropbox/Personnel/Devs/nicolas-hoizey.com
       Destination: /Users/nhoizey/Dropbox/Personnel/Devs/nicolas-hoizey.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
             Error: could not read file /Users/nhoizey/Dropbox/Personnel/Devs/nicolas-hoizey.com/_posts/2008/07/25-catching-the-sun/2004-09-26-Catching-the-sun.jpg: invalid byte sequence in UTF-8
```

I added other images too, today, without issue.

So , IMHO, there must be something in the image itself that causes the issue.

**Comment by DirtyF** [comment] 2017-01-16 15:25
same thing with jekyll 3.3.1

**Comment by nhoizey** [comment] 2017-05-04 14:52
Just understood why I had this error with these two files: it's because the file names were starting with dates.

I suppose Jekyll was messing with these files, thinking they were posts.

So… I don't have the issue anymore after [renaming the image files](https://github.com/nhoizey/nicolas-hoizey.com/commit/721c0f84e9fa496b898e24da7868ea1cc7b605ee).

**Comment by RRMoelker** [comment] 2017-05-04 16:11
Good to hear that solved it for you @nhoizey. For me the exclude option works for now.

But these kinds of bugs are way to prevalent with Jekyll. Considering the time I have for the project, I'm quite committed to the tech. For others, maybe consider a more customizable library if you want to do anything custom.

**Comment by nhoizey** [comment] 2017-05-04 18:47
@RRMoelker I don't really understand what you mean with "a more customizable library", sorry.

**Comment by RRMoelker** [comment] 2017-05-04 20:35
Got into a bit of a rant. What I mean is that for anything more than the Jekyll standard blog, I don't find Jekyll is the right tool for the job. For me I probably would have been better off stiching a couple of node libraries together with Gulp or the like.

**Comment by nhoizey** [comment] 2017-09-22 19:04
Anyone still having this issue?

https://github.com/jekyll/jekyll/pull/6344 might fix it.

**Comment by RRMoelker** [comment] 2017-09-24 07:27
Yes, with Jekyll 3.6 the site is compiling without excluding the files in the Jekyll config. I do get errors during the build but those no longer halt the process.

So problem **fixed**,
though I'll keep my config so the build doesn't show any errors:

```
exclude:
  ...
  - _posts/**/*.jpg
  - _posts/**/*.png
  - _posts/**/*.gif
```

**Comment by nhoizey** [comment] 2017-09-24 08:57
Do you really get errors, or just informations? What is the color of the message?

If you exclude them, do it still copy them to the destination?

**Comment by DirtyF** [comment] 2017-09-24 09:50
FWIW here is a test of the current output in Jekyll **without** the plugin: 

```sh
~/code/jekyll/tests/default
❯ bundle exec jekyll -v
jekyll 3.6.0

~/code/jekyll/tests/default
❯ tree _posts
_posts
├── 2017
│   └── 07
│       ├── 2017-07-27-so-long-disqus-hello-webmentions.md
│       ├── dareboost-disqus-page-weight.png
│       └── disqus-guests.png
├── 2017-07-01-welcome-to-jekyll.markdown
├── 2017-08-25-new-post.markdown
└── 2017-08-26-another&post.markdown

2 directories, 6 files

~/code/jekyll/tests/default
❯ bundle exec jekyll build
Configuration file: /Users/frank/code/jekyll/tests/default/_config.yml
            Source: /Users/frank/code/jekyll/tests/default
       Destination: /Users/frank/code/jekyll/tests/default/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.451 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by nhoizey** [comment] 2017-09-24 10:04
@DirtyF awesome, thanks for the detailed test!

**Closed by nhoizey** 2017-09-24 10:04 UTC
Labels: bug

**Comment by noaham** [comment] 2018-05-02 23:28
Hi. I am having the exact same issue. Jekyll version `3.7.3`. My posts directory looks like

    _posts/
        2018-05-01-first-post.md
        2018-05-02-post-in-directory/
            2018-05-02-post-in-directory.md
            one.jpg
            two.jpg
        2018-05-03-another-post.md

Running `bundle exec jekyll build` gives the error

    Error: could not read file .../_posts/2018-05-02-post-in-directory/one.jpg: invalid byte sequence in UTF-8
    Error: could not read file .../_posts/2018-05-02-post-in-directory/two.jpg: invalid byte sequence in UTF-8

However, when I rename the directory containing the image files, I no longer get an error. I.e. with the following directory structure, everything is fine. 

    _posts/
        2018-05-01-first-post.md
        post-in-directory/
            2018-05-02-post-in-directory.md
            one.jpg
            two.jpg
        2018-05-03-another-post.md

**Comment by nhoizey** [comment] 2019-10-13 08:39
@noaham could you please tell us if you still have the issue, meaning we should re-open this issue?

**Comment by noaham** [comment] 2019-10-14 18:35
@nhoizey I'm not able to reproduce the issue, so it seems to be fixed.

**Comment by w1ne** [comment] 2023-01-09 16:36
https://github.com/jekyll/jekyll/issues/9249

I have the same problem in Jekyll 4.3.1.

**Comment by nhoizey** [comment] 2023-01-09 16:49
@w1ne I'm sorry, I never updated my plugins to Jekyll 4, and I don't use Jekyll (nor Ruby) anymore.

From the issue you link too, I understand it could be a bug in Jekyll, not this plugin?

**Comment by w1ne** [comment] 2023-01-09 16:56
Yes, it is definitely a Jekyll bug, not your plugin. But it is well documented in your repo :D So, I will still leave the link. 

Thank you!

**Comment by nhoizey** [comment] 2023-01-09 16:59
Ok, thanks @w1ne ! 🙏

**Comment by obskyr** [comment] 2024-02-11 21:46
[I've written a plugin](https://gist.github.com/obskyr/7cd50686e1223b6c33f150381a23a273) to work around this issue – using this plugin, you no longer need to manually `exclude` image files from `_posts/` and `drafts/`, *and* dates at the start of filenames works as one would expect. (It achieves this by copying those troublesome images over itself, rather than leaving it to Jekyll.)

I suppose this really *should* be patched in Jekyll upstream, but until then, this plugin works wonders for me!
